backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - label: "Page"
    name: "page"
    create: true
    slug: "{{slug}}"
    folder: "src/pages"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "page"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown", required: false}
      - label: "Sections"
        name: "sections"
        widget: "list"
        types:
          - label: "Images"
            name: "image"
            widget: object
            fields:
              - {label: Header, name: header, widget: string, default: "Image Gallery"}
              - {label: Template, name: template,widget: "select", options: ["Carousel", "SliderHero", "Slider", "Gallery"]}
              - {label: Container Type, name: container, widget: "select", options: ["full", "container"]}
              - {label: Identifiant css, name: cssid, widget: "string", required: false}
              - {label: Class css, name: cssclass, widget: "string", required: false}
              - label: Images
                name: images
                widget: list
                fields: [{label: "Title", name: "title", widget: "string", required: false},{label: Image, name: image, widget: image},{label: "Body", name: "body", widget: "markdown", required: false}]
          - label: "cards"
            name: "cards"
            widget: object
            fields:
              - {label: Header, name: header, widget: string, default: "Image Gallery"}
              - {label: Template, name: template,widget: "select", options: ["Columns", "Masonry", "Accordion"]}
              - {label: Container Type, name: container, widget: "select", options: ["full", "container"]}
              - {label: Identifiant css, name: cssid, widget: "string", required: false}
              - {label: Class css, name: cssclass, widget: "string", required: false}
              - label: Cards
                name: cards
                widget: list
                fields: [{label: "Title", name: "title", widget: "string", required: false},{label: Image, name: image, widget: image, required: false},{label: "Body", name: "body", widget: "markdown", required: false}]
          - label: "Spotlight"
            name: "spotlight"
            widget: object
            fields:
              - {label: Header, name: header, widget: string, default: "Spotlight", required: false}
              - {label: Template, name: template, widget: hidden, default: "Spotlight"}
              - {label: Container Type, name: container, widget: "select", options: ["full", "container"]}
              - {label: "Body", name: "body", widget: "markdown"}
              - {label: Identifiant css, name: cssid, widget: "string", required: false}
              - {label: Class css, name: cssclass, widget: "string", required: false}
          - label: "Form"
            name: "form"
            widget: object
            fields:
              - {label: Header, name: header, widget: string, default: "Form", required: false}
              - {label: Template, name: template, widget: hidden, default: "form"}
              - {label: Container Type, name: container, widget: "select", options: ["full", "container"]}
              - {label: Identifiant css, name: cssid, widget: "string", required: false}
              - {label: Class css, name: cssclass, widget: "string", required: false}
              - {label: Formulaire, name: formitem, widget: "relation", collection: forms, searchFields: title, valueField: title}
  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Location", name: "location", widget: "map" }
      - {label: Mainpitch, name: mainpitch, widget: list, fields: [{label: Title, name: title, widget: string}, {label: Description, name: description, widget: text}]}
  - name: "custompage"
    label: "Custom Page"
    files:
      - file: "src/pages/old/index.md"
        label: "Landing Page"
        name: "Index Page"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page"}
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Heading, name: heading, widget: string}
          - {label: Subheading, name: subheading, widget: string}
          - {label: Mainpitch, name: mainpitch, widget: object, fields: [{label: Title, name: title, widget: string}, {label: Description, name: description, widget: text}]}
          - {label: Description, name: description, widget: string}
          - {label: Intro, name: intro, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Blurbs, name: blurbs, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Text, name: text, widget: text}]}]}
          - {label: Main, name: main, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Image1, name: image1, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image2, name: image2, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image3, name: image3, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}]}
      - file: "src/pages/about/index.md"
        label: "About"
        name: "about"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/products/index.md"
        label: "Products Page"
        name: "products"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "product-page"}
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Heading, name: heading, widget: string}
          - {label: Description, name: description, widget: string}
          - {label: Intro, name: intro, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Blurbs, name: blurbs, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Text, name: text, widget: text}]}]}
          - {label: Main, name: main, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Image1, name: image1, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image2, name: image2, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image3, name: image3, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}]}
          - {label: Testimonials, name: testimonials, widget: list, fields: [{label: Quote, name: quote, widget: string}, {label: Author, name: author, widget: string}]}
          - {label: Full_image, name: full_image, widget: image}
          - {label: Pricing, name: pricing, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: string}, {label: Plans, name: plans, widget: list, fields: [{label: Plan, name: plan, widget: string}, {label: Price, name: price, widget: string}, {label: Description, name: description, widget: string}, {label: Items, name: items, widget: list}]}]}
  - name: "settings"
    label: "Settings"
    editor:
      preview: false
    files:
      - file: "src/settings/index.json"
        extention: "json"
        label: "Settings"
        name: "settings"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Logo, name: logo, widget: image}
          - {label: Description, name: description, widget: string}
          - {label: Brand Color, name: brandcolor, widget: string, default: "#ff4400"}
          - {label: Main Menu, name: mainmenu, widget: list, fields: [{label: Title, name: title, widget: string}, {label: Path, name: path, widget: string}]}
      - file: "src/settings/theme.json"
        extention: "json"
        label: "Theme"
        name: "theme"
        fields:
          - {label: Title, name: title, widget: hidden, default: "theme"}
          - {label: Logo, name: logo, widget: image}
          - {label: Primary Brand Color, name: brandcolorprimary, widget: string, default: "#ff4400"}
          - {label: Secondary Brand Color, name: brandcolorsecondary, widget: string, default: "#ff4400"}
          - {label: Menu top Type, name: menutopbartype, widget: "select", options: ["normal", "sticky"]}
      - file: "src/settings/menus.json"
        extention: "json"
        label: "Menus"
        name: "menus"
        fields:
          - {label: Title, name: title, widget: hidden, default: "menus"}
          - {label: Main Menu Top, name: mainmenu, widget: list, fields: [{label: Title, name: title, widget: string}, {label: Path, name: path, widget: string}]}
          - {label: Menu Footer, name: footermenu, widget: list, fields: [{label: Title, name: title, widget: string}, {label: Path, name: path, widget: string}]}
      - file: "src/settings/siteinfos.json"
        extention: "json"
        label: "Site Information"
        name: "siteinfos"
        fields:
          - {label: Title, name: title, widget: hidden, default: "siteinfos"}
          - {label: Site name, name: sitename, widget: string, default: "siteinfos"}
          - {label: Description, name: description, widget: string}
          - {label: Google Analitics code, name: gacode, widget: string}
          - {label: Logo, name: logo, widget: image}
  - label: "Form"
    name: "forms"
    create: true
    extention: "json"
    slug: "{{slug}}"
    folder: "src/forms"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "Form"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown", required: false}
      - label: "Elements"
        name: "elements"
        widget: "list"
        types:
          - label: "Texte Court"
            name: "text"
            widget: object
            fields:
              - {label: Title, name: title, widget: string, default: "Label", required: false}
              - {label: Template, name: template,widget: "select", options:[Text,TextArea,Email,Password]}
              - {label: Placeholder Type, name: placeholder,widget: string, default: "Label", required: false}
              - {label: Description Type, name: description,widget: string, default: "Description", required: false}
              - {label: Identifiant css, name: cssid, widget: "string", required: false}
              - {label: Class css, name: cssclass, widget: "string", required: false}
          - label: "Liste"
            name: "list"
            widget: object
            fields:
              - {label: Title, name: title, widget: string, default: "Label", required: false}
              - {label: Template, name: template,widget: "select", options: ["Select", "Radio", "Checkbox"]}
              - {label: Placeholder Type, name: placeholder,widget: string, default: "Label", required: false}
              - {label: Description Type, name: description,widget: string, default: "Description", required: false}
              - {label: Identifiant css, name: cssid, widget: "string", required: false}
              - {label: Class css, name: cssclass, widget: "string", required: false}
              - label: Valeurs
                name: values
                widget: list
                fields: [{label: "Valeur", name: "value", widget: "string"},{label: "Label", name: "label", widget: "string"}]
